
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.example.cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 37;
  public static final int EMPTY = 12;
  public static final int INTEGER = 31;
  public static final int UPDATE = 19;
  public static final int DBMS_SERVER = 25;
  public static final int FOR = 3;
  public static final int DELETE = 20;
  public static final int GREATER_THAN = 13;
  public static final int DBMS = 24;
  public static final int NOT = 10;
  public static final int IS = 4;
  public static final int AND = 23;
  public static final int IP = 26;
  public static final int VALIDATIONS = 7;
  public static final int EOF = 0;
  public static final int BOOLEAN = 33;
  public static final int EQUALS_TO = 15;
  public static final int error = 1;
  public static final int CRUD = 8;
  public static final int NULL = 11;
  public static final int DATASOURCE = 9;
  public static final int NUMBER = 36;
  public static final int CONTROLLER = 6;
  public static final int PASSWORD = 29;
  public static final int ERROR = 40;
  public static final int UNIQUE = 16;
  public static final int GET_ALL = 18;
  public static final int USERNAME = 28;
  public static final int LBRACE = 38;
  public static final int GET_BY = 22;
  public static final int SAVE = 21;
  public static final int FLOAT = 34;
  public static final int RBRACE = 39;
  public static final int DATABASE = 27;
  public static final int GET_BY_ID = 17;
  public static final int LONG = 32;
  public static final int STRING = 30;
  public static final int AS = 2;
  public static final int ENTITY = 5;
  public static final int LESS_THAN = 14;
  public static final int IDENTIFIER = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AS",
  "FOR",
  "IS",
  "ENTITY",
  "CONTROLLER",
  "VALIDATIONS",
  "CRUD",
  "DATASOURCE",
  "NOT",
  "NULL",
  "EMPTY",
  "GREATER_THAN",
  "LESS_THAN",
  "EQUALS_TO",
  "UNIQUE",
  "GET_BY_ID",
  "GET_ALL",
  "UPDATE",
  "DELETE",
  "SAVE",
  "GET_BY",
  "AND",
  "DBMS",
  "DBMS_SERVER",
  "IP",
  "DATABASE",
  "USERNAME",
  "PASSWORD",
  "STRING",
  "INTEGER",
  "LONG",
  "BOOLEAN",
  "FLOAT",
  "IDENTIFIER",
  "NUMBER",
  "STRING_LITERAL",
  "LBRACE",
  "RBRACE",
  "ERROR"
  };
}

